version: "3.8"

services:
  backend:
    build:
      context: ../
      dockerfile: ./docker/dockerfile/dockerfile
    ports:
      - "8000:8000"
      - "8081:8081"
    command: sh docker/scripts/start.sh
    volumes:
      - ../:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pradeep
      POSTGRES_DB: study-buddy

  redis:
    image: redis:latest
