version: "3.8"

services:
  backend:
    build:
      context: ../
      dockerfile: ./docker/dockerfile/dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pradeep
      POSTGRES_DB: study-buddy