# Generated by Django 4.2.21 on 2025-06-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_group_admin_groupmembers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
    ]
