# Generated by Django 4.2.21 on 2025-07-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_remove_group_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmembers',
            options={'default_related_name': 'related_group_members'},
        ),
    ]
